version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - jfood_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "7000:80"
    depends_on:
      - postgres
    networks:
      - jfood_net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: my-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "7001:8080"
    networks:
      - jfood_net

  sonarqube:
    image: sonarqube:latest
    container_name: my-sonarqube
    ports:
      - "7002:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    depends_on:
      - postgres
    networks:
      - jfood_net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    ports:
      - "7003:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jfood_net

volumes:
  pg_data:
  jenkins_home:

networks:
  jfood_net:
    driver: bridge
